### PR TITLE
Attempt to detect spammers who make their e-mail harder to detect

### PR DESCRIPTION
**Pull request by Glorfindel83**
Attempt to detect spammers who make their e-mail harder to ---read--- detect, e.g. `info @ charcoal-se . org`.

### CODE REVIEW

**Comment by j-f1** [comment]
A couple of suggestions:

- Maybe use `\s*` instead of `\s?` to detect multiple spaces
- Match `at` as well  as `@` (case insensitive)
- Match `dot` as well as `.` (case insensitive)
- Match `` `@` `` and other formatting methods

**Comment by teward** [comment]
Would this capture this, which I just observed on a spam message?  `"antonio.iosdevmate" &Gmail`

**Comment by Glorfindel83** [comment]
I have tried to implement @JF's suggestions, and came up with the following:

`(?<![=#\/])\b[A-z0-9_.%+-]+\W*(@|[aA][tT])\W*(?!(example|domain|site|foo|\dx)\W*(\.|[dD][oO][tT])\W*[A-z]{2,4})[A-z0-9_.%+-]+\W*(\.|[dD][oO][tT])\W*[A-z]{2,4}\b`

[Regex 101](https://regex101.com/r/5vzFow/1)

I'm hesitant to implement the example of Thomas; it looks too much like
valid code to me, for instance:

`if (name == "first.last" & gmailEnabled) {`

I also noticed the three regexes are slightly different. I think it makes
sense to have one global `EMAIL_REGEX` constant, which can be modified
before calling `regex.compile`, but I'd rather leave that to somebody who
*is* proficient in Python.

**Comment by angussidney** [comment]
I'd like to see some data before we merge this. Is anyone experienced enough with the SEDE to get some?

**Comment by Glorfindel83** [comment]
I think I am, but SEDE is too slow and doesn't support regexes, just the general SQL `LIKE` syntax.

**Comment by dorukayhan** [comment]
> SEDE is too slow and doesn't support regexes

We can work around that by unconditionally `SELECT`ing as many `Posts` as possible, downloading the resulting dataset, and then running regexes over it.

**Comment by ArtOfCode-** [comment]
That... would break SEDE.

**Comment by dorukayhan** [comment]
@ArtOfCode I mean, we can `SELECT * FROM Posts`, download the results as a .csv file, and test the regexes on that .csv file. That wouldn't break SEDE as it makes no online interaction other than a mere `SELECT`ion.

**Comment by SmokeDetector** [comment]
I've done it before, you can get any table 50k at a time from SEDE (or just
download the data dump).

**Comment by artofcode** [comment]
@dorukayhan: that would be @ArtOfCode- , not me ;-)

**Comment by ArtOfCode-** [comment]
o/ namesake :)

But yeah, @dorukayhan SEDE *really* doesn't like large numbers of records. You're likely to have trouble getting lots of posts from it.

**Pull request closed without merging**
