### PR TITLE
Update chatcommands.py

### PR DESCRIPTION
**Pull request by Victor-VosMottor**
Hi! I'm Victor VosMottor from StackExchange. I wrote a command that is equivalent of whatis and man commands in bash. I think it will be useful ;)

### CODE REVIEW

**Comment by teward** [comment]
I'm... a little curious why we need this when **all commands are explicitly documented already on our site** (https://github.com/Charcoal-SE/SmokeDetector/wiki/Commands#wiki-wrapper)

**Comment by teward** [comment]
Also, you need to keep in line with the Python standards we uphold to with PEP8 guidelines.  These're your code linting failures:

```
./chatcommands.py:2324:1: W293 blank line contains whitespace
./chatcommands.py:2325:1: W293 blank line contains whitespace
./chatcommands.py:2332:121: E501 line too long (275 > 120 characters)
./chatcommands.py:2333:121: E501 line too long (272 > 120 characters)
./chatcommands.py:2344:121: E501 line too long (353 > 120 characters)
./chatcommands.py:2349:121: E501 line too long (195 > 120 characters)
./chatcommands.py:2351:121: E501 line too long (145 > 120 characters)
./chatcommands.py:2352:121: E501 line too long (160 > 120 characters)
./chatcommands.py:2353:121: E501 line too long (147 > 120 characters)
./chatcommands.py:2355:121: E501 line too long (155 > 120 characters)
./chatcommands.py:2356:121: E501 line too long (125 > 120 characters)
./chatcommands.py:2357:121: E501 line too long (582 > 120 characters)
./chatcommands.py:2364:1: W391 blank line at end of file
```

**Review by teward — CHANGES_REQUESTED** [review]
Code linting failures.  Adhere to PEP8 standards (with the exception for Max Line Length that we agreed on, maxLength is 120)

```
./chatcommands.py:2324:1: W293 blank line contains whitespace
./chatcommands.py:2325:1: W293 blank line contains whitespace
./chatcommands.py:2332:121: E501 line too long (275 > 120 characters)
./chatcommands.py:2333:121: E501 line too long (272 > 120 characters)
./chatcommands.py:2344:121: E501 line too long (353 > 120 characters)
./chatcommands.py:2349:121: E501 line too long (195 > 120 characters)
./chatcommands.py:2351:121: E501 line too long (145 > 120 characters)
./chatcommands.py:2352:121: E501 line too long (160 > 120 characters)
./chatcommands.py:2353:121: E501 line too long (147 > 120 characters)
./chatcommands.py:2355:121: E501 line too long (155 > 120 characters)
./chatcommands.py:2356:121: E501 line too long (125 > 120 characters)
./chatcommands.py:2357:121: E501 line too long (582 > 120 characters)
./chatcommands.py:2364:1: W391 blank line at end of file
```

**Comment by NobodyNada** [comment]
If we do this, I think it would be better to have the documentation be a parameter to the `@command` decorator — that way we keep the command and the documentation together, and we don’t have to repeat all the aliases. Then the `whatis` command can just pull the command from the dictionary and return its documentation property.

However, I’m with Thomas on this one: although I have occasionally wished for a command like this, I think the harm outweighs the benefits. We already have thorough documentation on our wiki, and it’s easy enough to just run `!!/help`, click the link, and Ctrl+F for the command you need. I’d rather not have to maintain two independent copies of the same documentation, because people will update one and forget to update the other.

Also, just for future reference, please use more helpful commit messages than “Update chatcommands.py”. I know that’s GitHub’s default, but that’s a really unhelpful message — if I’m going through a blame, I don’t need to be reminded about the name of the file I’m already looking at. Rather, a commit message should summarize exactly what was changed and why. See [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/). Thanks :)

**Pull request closed without merging**
