### PR TITLE
Implement a Windows wrapper class for "Git"

### PR DESCRIPTION
**Pull request by teward**
This should permit any of the 'git' functions we already use to work mostly out of the box, with one or two exceptions where we need to do a platform check in the code base, to work.  This makes Smokey Windows-compatible with all functions.

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
Looks okay to me, but @AWegnerGitHub might be a better person to review this

**Comment by teward** [comment]
Yeah we are going to do further checks today or this weekend with full Smokey creds.  We know this works fine for got status though - we need to test actual blacklisting now, though.

**Comment by AWegnerGitHub** [comment]
I stuck myself on this as a reviewer. As mentioned above, we're planning on testing in the next few days.

**Comment by teward** [comment]
I'm merging this now, and will fix it later if things break.  Testing on the git branch it's on is causing some headaches, and code reverts which blow things up when testing blacklisting functions, etc. so it'd be better to have this and then remove it later if it doesn't work, similar to what we've done for other 'radical changes' we've implemented.

**Pull request merged**
