### PR TITLE
Use personal access token

### PR DESCRIPTION
**Pull request by Daniil-M-beep**

### CODE REVIEW

**Comment by makyen** [comment]
This change appears to orphan `auth` (i.e. it's no longer used), which should be removed at the same time.

**Comment by Daniil-M-beep** [comment]
> This change appears to orphan `auth` (i.e. it's no longer used), which should be removed at the same time.

I don't see `auth` being used anywhere

**Comment by makyen** [comment]
Yes, exactly. With this change `auth` is no longer used. The line:
```
auth = HTTPBasicAuth(GlobalVars.github_username, GlobalVars.github_password)
```
should be removed at the same time as this change, which is the change that causes it to no longer be used.

**Comment by Daniil-M-beep** [comment]
> Yes, exactly. With this change `auth` is no longer used. The line:
> 
> ```
> auth = HTTPBasicAuth(GlobalVars.github_username, GlobalVars.github_password)
> ```
> 
> should be removed at the same time as this change, which is the change that causes it to no longer be used.

Done

**Comment by makyen** [comment]
!!/approve

**Pull request merged**
