### PR TITLE
Throttle less important messages (incomplete)

### PR DESCRIPTION
**Pull request by iBug**
This is an implementation of feature request #1735.

I plan to do this by adding another "throttled message queue" (TMQ). Messages in TMQ will be extracted and squashed into one when necessary. Debug messages and MS messages will go to this queue by default. Usually, this should have little to no effect on Smokey's behavior, but when there's a lot of debug messages, it will make a difference.

I'll be working on this FR/PR in the next few days, and drop the *incomplete* notice from the title after I think I've done.

### CODE REVIEW

**Comment by angussidney** [comment]
FYI, markdown doesn't render in multiline chat messages, which may mean that collapsing the messages into one isn't the right solution.

**Comment by iBug** [comment]
@angussidney The what about using things like a slash as a separator instead of newlines?

**Comment by NobodyNada** [comment]
@iBug If we collapse them into a single-line message, we’ll run into the message length limit pretty quickly.

**Comment by iBug** [comment]
I'll restart this if it's later found needed,

**Pull request closed without merging**
