### PR TITLE
Show username is similar to which website

### LINKED ISSUE #1655: Give position information when detecting URI similar to user name
Can we give position information when replying `sd why` to SD reports detecting URI similar to user name?  There are times when the URI is in code like [this example](https://metasmoke.erwaysoftware.com/post/108200)

### PR DESCRIPTION
**Pull request by iBug**
We currently have only this text for the reason:

```
Post - Username similar to website
```

It isn't very clear in some cases.

Resolves #1655

### CODE REVIEW

**Comment by NobodyNada** [comment]
This PR seems to be missing some commits?

**Comment by iBug** [comment]
Anyone know what CodeClimate is talking about?

**Comment by ArtOfCode-** [comment]
Ready to merge?

**Comment by iBug** [comment]
@ArtOfCode- Yes. Ready and tested.

**Comment by ArtOfCode-** [comment]
!!/approve

**Pull request merged**
