### PR TITLE
iBug: Blacklist BelleSilk

### PR DESCRIPTION
**Pull request by SmokeDetector**
[iBug](http://chat.stackexchange.com/users/275329) requests the blacklist of the keyword BelleSilk. See the Metasmoke search [here](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=BelleSilk) and the Stack Exchange search [here](https://stackexchange.com/search?q=%22BelleSilk%22).

### CODE REVIEW

**Comment by iBug** [comment]
Close this and go to #1543

**Comment by magisch** [comment]
!!/reject

**Comment by ArtOfCode-** [comment]
Rejected

**Comment by iBug** [comment]
reject

**Pull request closed without merging**
