### PR TITLE
Change %-formatting to {}-formatting

### PR DESCRIPTION
**Pull request by michaelb958**
So I'm told that %-formatting is officially a thing that should not be
used in new code(tm), and I figured this was a half-decent way to
acquaint myself with the codebase.

### CODE REVIEW

**Comment by ProgramFOX** [comment]
That's interesting! Where is its deprecated-ness stated?

**Comment by normalhuman** [comment]
@ProgramFOX  This seems to be the official source https://www.python.org/dev/peps/pep-3101/ 
It seems one has to be careful around Unicode vs non-Unicode strings, but all of ours are already Unicode: http://stackoverflow.com/a/12252460

**Comment by kevin-brown** [comment]
> Where is its deprecated-ness stated?

It's not deprecated yet, it's just _preferred_ to use the new `string.format` over the old overloaded `%` operator.

You might find the following interesting: [Pythons many ways of string formatting — are the older ones (going to be) deprecated?](http://stackoverflow.com/q/13451989/359284)

**Comment by ProgramFOX** [comment]
I think this can be merged. Does everyone else agree?

**Comment by Undo1** [comment]
@ProgramFOX  Looks good to me.

**Comment by normalhuman** [comment]
@ProgramFOX  No objections from me.

**Comment by Undo1** [comment]
In that case, I'm doing it. Let's break stuff.

**Comment by hichris1234** [comment]
Late :+1: from me. ;)

**Pull request merged**
