### PR TITLE
improve a number matcher in watched keywords

### PR DESCRIPTION
**Pull request by micsthepick**
don't match an ipv6 format, make sure we only start matching on the first digit.

### CODE REVIEW

**Comment by micsthepick** [comment]
some more info - I expect this to cause at least one less FP, and it should not remove any TP. If it does then I'll review

**Comment by micsthepick** [comment]
Metrics:
Before: TP: 1067 FP: 8 NAA: 0
After: TP: 1067 FP: 7 NAA: 0

**Comment by makyen** [comment]
I'm confused. This says that it's "improve a number matcher", which implies that it's *changing* something, but the change to the watchlist is to only add an entry. Was something already removed somewhere else?

**Comment by micsthepick** [comment]
Seems to have gotten lost in the rebasing, will check this @makyen

**Comment by micsthepick** [comment]
actually, this may have been something that I noticed for two reasons, it looks like one of the migrations to watched_numbers makes this PR redundant

**Comment by micsthepick** [comment]
relevant info: #13187

**Pull request closed without merging**
