### PR TITLE
Adds new character_utilization_ratio function to check if a single

### PR DESCRIPTION
**Pull request by AWegnerGitHub**
Adds new character_utilization_ratio function to check if a single character is over used in a post.

Initially only active on judaism.stackexchange.com

### CODE REVIEW

**Comment by AWegnerGitHub** [comment]
If we aren't using the codeclimate checks, can we remove it from CI?

**Comment by Undo1** [comment]
!!/aprove

**Comment by Undo1** [comment]
!!/approve

**Comment by Undo1** [comment]
Ignoring the CodeClimate thing for now. Need to figure out what we're doing with it.

**Pull request merged**
