### PR TITLE
tripleee: Blacklist mag-manager\.com

### PR DESCRIPTION
**Pull request by SmokeDetector**
tripleee requests blacklist of domains: 

 - mag-manager\.com

### CODE REVIEW

**Comment by AWegnerGitHub** [comment]
Do **not** merge this yet. Magneto is requesting the blacklist be accompanied with a rep check for users with 1 rep.

**Comment by ArtOfCode-** [comment]
@AWegnerGitHub Aren't blacklisted websites combined with a rep check already?

**Comment by magisch** [comment]
Looks like the max rep for the blacklisted website rule to apply is 50. From findspam.py:

```
        # Blacklisted sites
        {'regex': u"(?i)({})".format("|".join(blacklisted_websites)), 'all': True,
         'sites': [], 'reason': "blacklisted website in {}", 'title': True, 'body': True, 'username': False, 'stripcodeblocks': False, 'body_summary': True, 'max_rep': 50, 'max_score': 5},
```

**Comment by AWegnerGitHub** [comment]
Good find @magisch. 

Unfortunately, they report 50 is much higher than they want for this report. They are only seeing the problem with new, 1 rep users.

**Comment by digitalpianism** [comment]
Thanks for that everyone. Yeah every user causing this particular problem is 1 reputation. I don't mind making it 50 rep as we can deal with a few false positive ;)

**Comment by ArtOfCode-** [comment]
I don't think we're going to see many false positives from this. Since Magento (their representative, anyway) is okay with 50 rep, I'm going to merge this.

**Pull request merged**
