### PR TITLE
Replace Travis CI badge with GitHub Actions badge

### PR DESCRIPTION
**Pull request by mbrukman**

### CODE REVIEW

**Comment by fastnlight0** [comment]
How about using shields.io for the for-the–badge style?

Build

CircleCI

Coveralls

GitHub Issues

GitHub Pull Requests

**Comment by makyen** [comment]
@fastnlight0 In order to compare your proposed badges from shields.io with what we currently have, I created a couple of tables:

| current | shields.io |
|----|-----|
| [Build Status](https://github.com/Charcoal-SE/SmokeDetector/actions/workflows/build.yml?query=branch%3Amaster) | Build |
| [Circle CI](https://circleci.com/gh/Charcoal-SE/SmokeDetector) | CircleCI |
| [Coverage Status](https://coveralls.io/github/Charcoal-SE/SmokeDetector?branch=master) | Coveralls |
| [Open issues](https://github.com/Charcoal-SE/SmokeDetector/issues) | GitHub Issues |
| [Open PRs](https://github.com/Charcoal-SE/SmokeDetector/pulls) | GitHub Pull Requests |

|  |  |
|--|--|
| current | [Build Status](https://github.com/Charcoal-SE/SmokeDetector/actions/workflows/build.yml?query=branch%3Amaster) [Circle CI](https://circleci.com/gh/Charcoal-SE/SmokeDetector) [Coverage Status](https://coveralls.io/github/Charcoal-SE/SmokeDetector?branch=master) [Open issues](https://github.com/Charcoal-SE/SmokeDetector/issues) [Open PRs](https://github.com/Charcoal-SE/SmokeDetector/pulls) |
| shields.io| Build CircleCI Coveralls GitHub Issues GitHub Pull Requests |

Personally, I prefer the current badges.

**Comment by fastnlight0** [comment]
At the end of the day, it's up to personal preference. While I prefer the shields.io badges, it's your pick which one you wish to use.

**Comment by makyen** [comment]
@fastnlight0 I'm willing to have other people weigh-in on their preferences, and have us choose some method of deciding which to use. However, this conversation is *much* more appropriate to have as an Issue, rather than in comments on a PR which wasn't for the express purpose of making the change. If you want, you're welcome to create an Issue to discuss this.

**Pull request merged**
