### PR TITLE
Jamal: Blacklist supplementstest\.org

### PR DESCRIPTION
**Pull request by SmokeDetector**
[Jamal](http://chat.stackexchange.com/users/76076) requests the blacklist of the website supplementstest\.org. See the Metasmoke search [here](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=supplementstest\.org)

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
Already caught as a pattern-matching website.

**Comment by dorukayhan** [comment]
This commit puts the regex on [line 854](https://github.com/Charcoal-SE/SmokeDetector/blob/master/blacklisted_websites.txt#L854) which is already populated by another regex. I think that's what causes the merge conflict.

**Comment by Undo1** [comment]
Merge conflict doesn't matter, but as Art says it's already caught so closing.

**Comment by Fortunate-MAN** [comment]
Just a note: [this](http://chat.stackexchange.com/transcript/message/35215421#35215421) and the next chat message is related to this.

**Comment by JamalAlmouslli** [comment]
Where was it listed before?  I didn't see it in blacklisted_websites.txt, and I don't believe SD ever caught it automatically.

**Comment by Undo1** [comment]
@JamalAlmouslli It's caught by a regex, probably https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L299

**Comment by JamalAlmouslli** [comment]
Oh, okay.  I thought all website had to be made explicit.  Maybe SD's failure to report that question was just a hiccup, unless it can take over a minute to report something.

**Comment by Undo1** [comment]
Which question was it, @JamalAlmouslli? Could have been in the API queue, but questions matching an obvious regex are usually caught immediately at the websocket level.

**Comment by JamalAlmouslli** [comment]
http://apple.stackexchange.com/questions/271629

**Pull request closed without merging**
