### PR TITLE
Add Marlin Woods to username blacklist

### PR DESCRIPTION
**Pull request by bwDraco**
We're getting a flood of posts containing plagiarized content from unregistered accounts with the username "Marlin Woods" on Super User. Each post is on a separate unregistered account. See http://meta.superuser.com/questions/11908/flood-of-plagiarized-answers-from-marlin-woods.

### CODE REVIEW

**Comment by Fortunate-MAN** [comment]
I don't think Smokey is for detecting plagiarized posts. AFAIK, this user is only plagiarizing content and not posting trolls or spam, which Smokey is intended to.

IMO, this shouldn't be merged as the user is **not** posting trolls or spam AFAIK.

**Comment by Undo1** [comment]
Tend to agree that this wouldn't fall under Smokey's focus.

**Comment by bwDraco** [comment]
Well, this is a bit of an edge case. It's getting referred to as trolling by others in the community, and the posts are disruptive because this is happening repeatedly and frequently, seemingly as to "play with" our moderation system by posting lots of inappropriate content that is hard to detect as such.

**Comment by Undo1** [comment]
After reviewing this some more, I've come to the conclusion that this edge case is something we should detect. They're a persistent (ish) troll that is copying the question into the answer box, which is bad.

**Comment by bwDraco** [comment]
For the benefit of readers, there was a typo in this code change which was fixed in [this pull request](https://github.com/Charcoal-SE/SmokeDetector/pull/296).

**Pull request merged**
