### PR TITLE
Watchlist additions

### PR DESCRIPTION
**Pull request by Glorfindel83**

### CODE REVIEW

**Comment by quartata** [comment]
!!/approve

**Comment by quartata** [comment]
....not sure why it's waiting on CircleCI since that doesn't run on PRs, but I'm guessing this won't automatically merge without Metasmoke

**Comment by ArtOfCode-** [comment]
It wouldn't automatically merge anyway, even if metasmoke was functioning

**Comment by ArtOfCode-** [comment]
!!/approve

**Pull request merged**
