### PR TITLE
Adds named args to several function calls

### PR DESCRIPTION
**Pull request by AWegnerGitHub**
This updates calls to `handle_spam`, `check_if_spam`, `post_message_in_room` and `handle_commands` to use named parameters instead of positional parameters.

### CODE REVIEW

**Comment by Undo1** [comment]
I really like this, is a lot more readable to me. Let's see what the others think.

**Comment by ProgramFOX** [comment]
+1 from me

**Comment by ArtOfCode-** [comment]
+11 from me

**Comment by Undo1** [comment]
If there are no major objections by noon US time, I'm going to very strong consider (read: will) merging this.

**Comment by normalhuman** [comment]
belated +1

**Pull request merged**
