### PR TITLE
Ashish Ahuja: Blacklist intl\.aliyun\.com

### PR DESCRIPTION
**Pull request by SmokeDetector**
[Ashish Ahuja](http://chat.stackexchange.com/users/181293) requests the blacklist of the website intl\.aliyun\.com. See the Metasmoke search [here](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=intl\.aliyun\.com)

### CODE REVIEW

**Comment by Fortunate-MAN** [comment]
Just close this. Magisch just blacklisted `aliyun.com`.

**Comment by ArtOfCode-** [comment]
Other way round :)

**Comment by Fortunate-MAN** [comment]
heh, didn't notice that. Also, have the code privs changed?

**Comment by Fortunate-MAN** [comment]
Weird.. I do [have code privs](https://metasmoke.erwaysoftware.com/users) (see user 26), but still it created a PR.. bug?

**Comment by ArtOfCode-** [comment]
Not sure what's going on there.

**Comment by Fortunate-MAN** [comment]
The code privs seemed to work for Magisch though; seems like a bug related to my account. Need to go to sleep now though, busy day for me tomorrow.

**Comment by Fortunate-MAN** [comment]
Actually, I had an account merge recently. Is that something related to this? My user-id and chat-id changed recently..

**Pull request merged**
