### PR TITLE
add "slut" to offensive regex

### PR DESCRIPTION
**Pull request by alexander-liao**
"slut" with any number of "t"s, optionally followed by a "y"

### CODE REVIEW

**Comment by teward** [comment]
This is effectively a duplicate of #1649

**Comment by teward** [comment]
While this is a good idea, I want to be sure we don't catch any odd cases of false positives.  It's far easier to update the blacklists than it is to adjust the regex here, so for *now* I'm rejecting this suggestion here.

**Comment by angussidney** [comment]
The whole reason why we have an offensive regex is for offensive words. Adding this to the blacklist doesn't make it any easier to edit/remove - either way it still requires someone with git access.

**Comment by angussidney** [comment]
!!/approve

**Pull request merged**
