### PR TITLE
Plop!

### PR DESCRIPTION
**Pull request by dorukayhan**
Added a command that replies with "Plop!".

The problem is, since I have no idea which function retrieves commands and executes things accordingly, I don't know where to call command_plop when someone says !!/plop...

### CODE REVIEW

**Comment by hichris1234** [comment]
Not only does this not pass CI, I really don't think more "fun" commands are a good use of our time.

**Comment by ByteCommander** [comment]
And how would this be useful? Why would we want to add that? I don't see any reason. It isn't even funny - at least to me...

**Comment by Undo1** [comment]
For the sake of education, you would place this in https://github.com/Charcoal-SE/SmokeDetector/blob/master/chatcommands.py#L1148.

Agree that it probably isn't something we want/need, though.

**Comment by ArtOfCode-** [comment]
@dorukayhan Awesome that you want to contribute, but the others have said it - we've got enough fun commands these days. Your effort is probably better spent looking for websites we can blacklist, or patterns of spam that we can pick up.

**Pull request closed without merging**
