### PR TITLE
Add a !!/watch-keyword command

### PR DESCRIPTION
**Pull request by tripleee**
Matches on this keyword list will trigger a rule "potentially bad keyword" which is separate from "bad keyword" and is intended to have a lower barrier than outright blacklisting.

Basically, if you want to be alerted when "something" comes up, Smokey can now do that.

Items on the watched keyword list are annotated with a date stamp to allow an administrator to prune the list periodically (down the line we might want to add code to do this automatically, too).

### CODE REVIEW

**Comment by tripleee** [comment]
Those CI failures seem rather draconian, is there any way to tweak them down from "failure" to "warning" or something?

**Comment by ArtOfCode-** [comment]
No, but we can always just override and merge anyway :)

**Comment by angussidney** [comment]
What's the difference between this and blacklisted keywords? Both will trigger a report on their own, so it's not like this one has a lower potential impact than blacklisted keywords.

**Comment by tripleee** [comment]
The primary intent is to allow us to `!!/watch-keyword` when we don't have sufficient evidence to directly blacklist something.  I keep on making mental notes, bookmarks, notes to self etc on things which I am reasonably convinced are going to crop up again soon, but it's a hassle.  Being able to say "please remind me to go ahead and blacklist" is the primary feature here; we should definitely take care to ensure that we don't have things both in a watchlist and blacklisted at the same time (probably programmatically, eventually).

I'd be fine with artificially giving this a zero weight if that seems to be necessary and/or helpful.

**Pull request merged**
