### PR TITLE
iBug: Blacklist muscle\W?enhancer?

### PR DESCRIPTION
**Pull request by SmokeDetector**
[iBug](http://chat.stackexchange.com/users/275329) requests the blacklist of the keyword muscle\W?enhancer?. See the Metasmoke search [here](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body=muscle+%3Fenhancer%3F) and the Stack Exchange search [here](https://stackexchange.com/search?q=%22muscle+%3Fenhancer%3F%22).

### CODE REVIEW

**Comment by iBug** [comment]
SE search: [No result](https://stackexchange.com/search?q=%22muscle+enhance%22) for **muscle enhance**, [TP only](https://stackexchange.com/search?q=%22muscle+enhancer%22) for **muscle enhancer**.

**Comment by teward** [comment]
I hate to ask the obvious, but what makes this an effective blacklist beyond what we already have?

Consider [this](https://metasmoke.erwaysoftware.com/post/100213) spam post which would match with the proposed blacklist.  This same spam post is already captured by the following detection filters:

```
Title - Position 1-7: Muscle
Body - Position 4-18: Core Max Ultra
Body - Position 21-35: Core Max Ultra
Body - Position 769-783: Core Max Ultra
Body - Position 980-994: Core Max Ultra
Body - Position 1707-1721: core-max-ultra
Body - Position 1782-1796: core-max-ultra
Body - Position 628-644: weight-reduction
Body - Position 1585-1596: weight loss
Body - Position 1689-1706: supplimenttop.com
Body - Position 1764-1781: supplimenttop.com
Post - Bad fragment in link http://supplimenttop.com/core-max-ultra-review/
Post - Link at end: http://supplimenttop.com/core-max-ultra-review/
```

My only question is, how does this improve upon existing detections?  Is there anything not caught by other filters which already exist that this one specifically catches?

**Comment by iBug** [comment]
**UPDATE**: The zero MS hit is misleading. [The correct search](https://metasmoke.erwaysoftware.com/search?utf8=✓&body=muscle+%3Fenhancer%3F&body_is_regex=1) (with RegEx enabled) shows 33 TPs and zero FPs.

**Comment by teward** [comment]
@iBug You didn't answer my question.  How does this improve upon existing lists, because we have other filters which would capture these things.  Further, is there anything *not* already caught that this proposed blacklist entry would catch that isn't caught by another filter already?

**Comment by iBug** [comment]
@teward There's quite a few ~280 near-boderline hits. This addition will improve that.

**Comment by AWegnerGitHub** [comment]
"near-borderline"? What does that mean?

**Comment by AWegnerGitHub** [comment]
Due to the above, I'm going to reject this.

**Pull request closed without merging**
