### PR TITLE
Use plain text for queue timings data

### PR DESCRIPTION
**Pull request by user12986714**
Used plain text format for storing queue timings data, rather than pickle, to reduce unnecessary disk I/O.

Potentially solved issue #3243 .

### CODE REVIEW

**Comment by user12986714** [comment]
One conflict in bodyfetcher.py with master branch. Simply deleting the conflicting code in master branch would resolve this issue.

**Comment by user12986714** [comment]
@ArtOfCode- I believe that it is generally not a good idea to merge master into a PR, as learned [here](https://github.com/Charcoal-SE/SmokeDetector/pull/3860#issuecomment-633127220). Therefore I reverted your last commit. If there are good reasons that I am not aware of for doing so, you may want to reset HEAD to `1e74aae6745b10fb44f429bba075d1d03faf880b` and force push to recover it.

**Comment by ArtOfCode-** [comment]
Merging master into a PR is how you resolve merge conflicts. Removing that commit means there are now merge conflicts with this PR again; you're welcome to resolve them another way.

**Comment by makyen** [comment]
This currently appears to grow the bodyfetcherQueueTimings.txt log file without bound, and without handling errors or potential corruption in the file. At an absolute minimum, we need to have a handle on how rapidly this will consume disk space, and some way for the file to be truncated or reset. As to how much disk space it will use, I plan to run this on an instance for a few hours to get an idea of the amount of space used.

Note: My instances already encountered a disk space issue, which has been temporarily alieviated on my end. I have a planned change to SD, which should solve that separate issue, but which I still need to test.

**Comment by user12986714** [comment]
Given the limit in API quota, SD will make no more that 20k requests per day. As seen in queuing config, each API call should log no more than 10 lines of data. Each line of data, given the worst case, would not be exceeding 100 Bytes. Hence the disk write cost for one day is no more that 20 MB, which is a significant reduce compared to 2 MB *per API call* in the previous implementation.  

As for the disk space problem, the plain text format will not be occupying order of magnitude of more disk space than the serialized pickle. Hence it is expected that in this implementation the disk space cost per day is no more that 9 times of that of the original implementation, and my personal guess is no more than 1.2 times, which is not really a severe issue.  

It is also true that logs, on POSIX, is cleaned manually by an admin or by a cron job, not by the application generating it. Implementing the feature of log size control would add unnecessary logic to the code, as cron is already doing a good enough job in automating log size control.  

Stepping back, given the calculation in the first paragraph, which indicates no more than 20 MB writes per day, effectively tells us that for 1 GB of disk space SD may run at least 50 days. Given that on modern computers, even on RPis, it is common to have disk space of several GBs, I don't really see the point for auto log size control.

**Comment by makyen** [comment]
This is currently broken. The merge of the master branch into this one broke it (posts are not scanned).

This can be reopened once the problem is resolved.

**Pull request closed without merging**
