### PR TITLE
Potential Code Re-Factor and Bug Fixes

### PR DESCRIPTION
**Pull request by HarshCasper**
## Summary

This pull request: 

- Remove unnecessary comprehension
- Change methods not using its bound instance to staticmethods
- Use literal syntax instead of function calls to create data structure

## Importance

I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/SmokeDetector/).

DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes. If you want to setup DeepSource for Continuous Analysis, I can help you set that up.

### CODE REVIEW

**Comment by tripleee** [comment]
Thanks for this patch!

The overall diff is surprisingly small; I guess we are in pretty good shape by this metric.

I have a vague objection to the `@staticmethod` changes which I will probably need to articulate better if I really want to argue my case, but other than that, this seems good to go in.

**Review by ArtOfCode- — APPROVED** [review]

**Comment by teward** [comment]
This may be approved by Art and others, however I'd like to take your patch and run some runtime tests with TCoM (The Call of Midnight, my dev testing SmokeDetector instance).  the reason for this is I fiddled with making things StaticMethods before and it totally exploded the infrastructure - so forgive me for putting a temporary "Needs Changes" review on this.

**Review by teward — CHANGES_REQUESTED** [review]
See comments - this review may change after testing/review/digging in the dev instance.

**Review by teward — APPROVED** [review]

**Review by makyen — CHANGES_REQUESTED** [review]
* What benefits do you see us getting from using the DeepSource service?
* What is your relationship to DeepSource? Why are you recommending it?
* To use DeepSource, it appears we are required to give them write access to our repository. I am not comfortable with that at this time, even though they say they only need write access to a single file.

**Comment by ArtOfCode-** [comment]
@makyen here's the install dialog:

image

IOW, while write access is required, it's enforced to `.deepsource.toml` by GitHub, rather than being "all files but promise we'll only edit one".

FWIW, my review above was purely code-only - agree with your concerns.

**Comment by teward** [comment]
> * What benefits do you see us getting from using the DeepSource service?
> * What is your relationship to DeepSource? Why are you recommending it?
> * To use DeepSource, it appears we are required to give them write access to our repository. I am not comfortable with that at this time, even though they say they only need write access to a single file.

My suggestion: keep the code changes, rip out the deepsource config.  We don't *need* to use the service if we don't want to, for privacy, etc. concerns.

**Pull request closed without merging**
