### PR TITLE
Morning routine 20170703

### PR DESCRIPTION
**Pull request by tripleee**
Batching a number of edits to avoid multiple restarts.

### CODE REVIEW

**Comment by tripleee** [comment]
!!/approve

**Comment by ArtOfCode-** [comment]
Approvals are there to have more than one pair of eyes on a PR, so self approving kinda defeats that. PullApprove should have ignored it, but maybe the config was wrong.

**Comment by angussidney** [comment]
@ArtOfCode- but similarly, Tripleee could have made these changes directly to master, but batched them together in order to save resources, so another approval isn't really necessary.

**Comment by tripleee** [comment]
I agree that the PR was sort of gratuitous in this situation, though. I did my morning routine this morning just by merging locally. (Though a PR would have helped avoid a problem I managed to introduce, by running the test suite before merging. But I'll keep that in mind to include in my local routines from now on.)

**Pull request merged**
