### PR TITLE
Remove duplicates

### PR DESCRIPTION
**Pull request by iBug**
Remove duplicated phone number pattern according to [Issue #1442](https://github.com/Charcoal-SE/SmokeDetector/issues/1442). Minor merges.

### CODE REVIEW

**Comment by iBug** [comment]
Bad maths for me. Please change Line #233 to 

```
\+?234\W*\d{3}\W*\d{3}\W*\d{2,8}
```

**Comment by tripleee** [comment]
Maybe just drop the plus sign actually, or maybe even move the generic Nigerian pattern to the watch list instead.

**Comment by iBug** [comment]
@tripleee PR updated.

**Comment by tripleee** [comment]
Thanks for the update, but now the 234* phone numbers which used to be blacklisted are no longer blacklisted. I'm fine with moving the generic +234 detection to watch but then the individual numbers we have blacklisted should remain blacklisted.

Sorry to be a pest, I appreciate the effort, and sorry I have not been able to communicate my intents properly.

**Comment by iBug** [comment]
@tripleee I understood your request. I've made changes correspondingly.

**Pull request merged**
