### PR TITLE
FrankerZ: Watch print\("SyntaxError: invalid syntax"\)\W*

### PR DESCRIPTION
**Pull request by SmokeDetector**
[FrankerZ](https://chat.stackexchange.com/users/224538) requests the watch of the watch_keyword `print\("SyntaxError: invalid syntax"\)\W*`. See the MS search [here](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=print%5C%28%22SyntaxError%3A+invalid+syntax%22%5C%29%5CW%2A) and the Stack Exchange search [here](https://stackexchange.com/search?q=%22print%5C%28%22SyntaxError%3A+invalid+syntax%22%5C%29+%2A%22).

### CODE REVIEW

**Comment by danbopes** [comment]
Per Mayken's response [here](https://github.com/Charcoal-SE/SmokeDetector/pull/2660), added `\W*`.

**Comment by makyen** [comment]
I'm going to approve this. I have a significant reluctance to watching for code, but we can try this for a while and see if it's useful.
!!/approve

**Comment by makyen** [comment]
!!/approve

**Comment by ArtOfCode-** [comment]
!!/approve

**Comment by makyen** [comment]
Thanks @ArtOfCode- I switched to doing something else to wait for CI to verify, then managed to forget to come back to merge.

**Pull request merged**
