### PR TITLE
Add Owen Hines to Charcoal --autopull

### PR DESCRIPTION
**Pull request by Fortunate-MAN**
SE link for reference: https://chat.stackexchange.com/users/238145

### CODE REVIEW

**Comment by superplane39** [comment]
!!/approve

**Comment by superplane39** [comment]
!!/approve

**Comment by Fortunate-MAN** [comment]
Closing this: https://github.com/Charcoal-SE/SmokeDetector/pull/1112

**Comment by angussidney** [comment]
@superplane39 MS will only automatically merge the PR if it was **both** made by Smokey, and only changes the blacklist.

**Pull request closed without merging**
