### PR TITLE
Shorten URL links

### PR DESCRIPTION
**Pull request by iBug**
Shorten URL for questions and users (I bet you folks don't know users link can be shortened to `/u/<UserID>`, so I bring it up here).

### CODE REVIEW

**Comment by quartata** [comment]
Why the test edits?

**Comment by iBug** [comment]
@quartata @AWegnerGitHub @teward I changed the old tests because they are no loner correct. The change is intended to make Smokey generate shorter links, and leaving old tests will only break the test because it won't generate longer links anymore.

**Comment by quartata** [comment]
You're going to need to change more functions in parsing to accommodate that most likely.

**Comment by quartata** [comment]
Also it would be nice if you would write proper commit messages so we know at a glance what a commit does.

**Comment by iBug** [comment]
@quartata I'll remember that next time. I've gone through the whole file and made sure everything's right

**Comment by iBug** [comment]
Wait, I messed something up while trying to edit commit messages.

**Comment by iBug** [comment]
@quartata @teward @AWegnerGitHub Updated all the changes. Please review.

**Comment by angussidney** [comment]
I’m not 100% sure, but some of the report parsing regexes/some userscripts rely on the message having unshortened links, make sure these aren’t broken by this change.

**Comment by quartata** [comment]
https://github.com/Charcoal-SE/SmokeDetector/blob/master/parsing.py#L182

**Comment by iBug** [comment]
@quartata Did you see the comment is edited in my patch?

**Comment by ArtOfCode-** [comment]
Pretty sure metasmoke relies on links having `/questions/` or `/a/` in them rather than the shortened form...

**`[status-don't-merge]`**

**Comment by iBug** [comment]
@ArtOfCode- Maybe change MS first, to let it recognize both `/questions/` and `/q/`, before merging this one.

**Comment by ArtOfCode-** [comment]
I'm gonna [status-declined] this one. Thanks for your work, @iBug, but given that this is likely to require metasmoke and userscripts changes as well and the gains are minimal, I don't think we win on the benefit/loss scales.

**Pull request closed without merging**
