### PR TITLE
Add FrankerZ to privileged list for SOCVR

### PR DESCRIPTION
**Pull request by danbopes**
Hope this is the correct way to request privileges. I've been in the SOCVR for a few months now, 3k+ rep, looking to help cleanup the site.

### CODE REVIEW

**Comment by hichris1234** [comment]
Paging @rschrieken.

**Comment by ArtOfCode-** [comment]
http://chat.stackoverflow.com/transcript/message/32037522#32037522

**Comment by rschrieken** [comment]
Is this a joke? I need to respond within two hours? Maybe you guys run a 24/7 ops butI have a life .. ;)

I trust gunr's call. No problem.

**Comment by ArtOfCode-** [comment]
@rschrieken Nah, I just had some free time so I figured I might as well see if I could find someone :)

**Pull request merged**
