### PR TITLE
No restart blacklists

### LINKED ISSUE #882: Blacklisting (watch etc) without restarting Smokey
`!!/blacklist` and related commands currently force SmokeDetector to exit with a particular exit code in order to reinitialize it with an updated blacklisting database.

This seems mildly excessive and moderately disruptive.  Updating the affected blacklist in memory would avoid some failure scenarios and probably improve the user experience.

### PR DESCRIPTION
**Pull request by angussidney**
Fixes #882

This is mostly done, but tests keep failing and I'm not sure why. By the looks of it, all of the blacklists are matching everything, which isn't intended. If someone could have a look, that'd be awesome.

Flow diagram:
- !!/blacklist commands - use the normal process, these will be pulled in automatically later
- !!/pull: check changed files
    - if only blacklist files changed, pull and reload blacklists
    - if anything else changed, follow the normal process (check CI etc)
- MS notifies of a new commit to deploy: check changed files
    - if changes other than blacklists, do nothing (wait for CI)
    - if only blacklists changed, check for issues (e.g. duplicate entries etc - these were originally part of `test_blacklist_integrity.py`, but since we are no longer doing CI on blacklist changes this needs to be checked manually)
        - if any issues, notify in chat of any problems and do nothing
        - if no issues, pull and reload blacklists

### CODE REVIEW

**Comment by tripleee** [comment]
I made a temporary patch to see which rules are matching.  The remaining test failures all seem to be because a regex is empty, or contains an empty fragment like `\b()\b|other|stuff`.
```
----------------------------- Captured stdout call -----------------------------
-- {'max_score': 1, 'username': True, 'stripcodeblocks': False, 'sites': [], 'max_rep': 4, 'body_summary': True, 'all': True, 'reason': 'bad keyword in {}', 'body': True, 'regex': '(?is)\\b()\\b|ಌ|vashi?k[ae]r[ae]n|babyli(ss|cious)|garcinia|cambogia|acai ?berr|(eye|skin|aging) ?cream|b ?a ?m ?((w ?o ?w)|(w ?a ?r))|online ?it ?guru|abam26|watch2live|cogniq|(serum|lift) ?eye|tophealth|poker[ -]?online|caralluma|male\\Wperf(?!ormer)|anti[- ]?aging|lumisse|(ultra|berry|body)[ -]?ketone|(cogni|oro)[ -]?(lift|plex)|diabazole|forskolin|tonaderm|luma(genex|lift)|(skin|face|eye)[- ]?(serum|therapy|hydration|tip|renewal|gel|lotion|cream)|(skin|eye)[- ]?lift|(skin|herbal) ?care|nuando[ -]?instant|\\bnutra|nitro[ -]?slim|aimee[ -]?cream|slimatrex|cosmitone|smile[ -]?pro[ -]?direct|bellavei|opuderm|contact (me|us)\\W*<a |follicure|kidney[ -]?bean[ -]?extract|ecoflex|\\brsgold|bellavei|goji ?xtreme|lumagenex|ajkobeshoes|kreatine|packers.{0,15}(movers|logistic).{0,25}</a>|guaranteedprofitinvestment|(brain|breast|male|penile|penis)[- ]?(enhance|enlarge|improve|boost|plus|peak)|renuva(cell|derm)| %uh | %ah |svelme|tapsi ?sarkar|viktminskning|unique(doc)?producers|green ?tone ?pro|troxyphen|seremolyn|revolyn|(?:networking|cisco|sas|hadoop|mapreduce|oracle|dba|php|sql|javascript|js|java|designing|marketing|salesforce|joomla)( certification)? (courses?|training).{0,25}</a>|(?:design|development|compan(y|ies)|training|courses?|automation)(\\b.{1,8}\\b)?\\L<city>\\b|Ｃ[Ｏ|0]Ｍ|ecoflex|no2factor|no2blast|sunergetic|capilux|sante ?avis|enduros|dianabol|ICQ#?\\d{4}-?\\d{5}|3073598075|lumieres|viarex|revimax|celluria|viatropin|(meg|test)adrox|nordic ?loan ?firm|safflower\\Woil|(essay|resume|article|dissertation|thesis) ?writing ?service|satta ?matka|b.?o.?j.?i.?t.?e.?r', 'title': True} bad keyword in title
-- {'max_score': 1, 'username': True, 'stripcodeblocks': False, 'sites': [], 'max_rep': 4, 'body_summary': True, 'all': True, 'reason': 'bad keyword in {}', 'body': True, 'regex': '(?is)\\b()\\b|ಌ|vashi?k[ae]r[ae]n|babyli(ss|cious)|garcinia|cambogia|acai ?berr|(eye|skin|aging) ?cream|b ?a ?m ?((w ?o ?w)|(w ?a ?r))|online ?it ?guru|abam26|watch2live|cogniq|(serum|lift) ?eye|tophealth|poker[ -]?online|caralluma|male\\Wperf(?!ormer)|anti[- ]?aging|lumisse|(ultra|berry|body)[ -]?ketone|(cogni|oro)[ -]?(lift|plex)|diabazole|forskolin|tonaderm|luma(genex|lift)|(skin|face|eye)[- ]?(serum|therapy|hydration|tip|renewal|gel|lotion|cream)|(skin|eye)[- ]?lift|(skin|herbal) ?care|nuando[ -]?instant|\\bnutra|nitro[ -]?slim|aimee[ -]?cream|slimatrex|cosmitone|smile[ -]?pro[ -]?direct|bellavei|opuderm|contact (me|us)\\W*<a |follicure|kidney[ -]?bean[ -]?extract|ecoflex|\\brsgold|bellavei|goji ?xtreme|lumagenex|ajkobeshoes|kreatine|packers.{0,15}(movers|logistic).{0,25}</a>|guaranteedprofitinvestment|(brain|breast|male|penile|penis)[- ]?(enhance|enlarge|improve|boost|plus|peak)|renuva(cell|derm)| %uh | %ah |svelme|tapsi ?sarkar|viktminskning|unique(doc)?producers|green ?tone ?pro|troxyphen|seremolyn|revolyn|(?:networking|cisco|sas|hadoop|mapreduce|oracle|dba|php|sql|javascript|js|java|designing|marketing|salesforce|joomla)( certification)? (courses?|training).{0,25}</a>|(?:design|development|compan(y|ies)|training|courses?|automation)(\\b.{1,8}\\b)?\\L<city>\\b|Ｃ[Ｏ|0]Ｍ|ecoflex|no2factor|no2blast|sunergetic|capilux|sante ?avis|enduros|dianabol|ICQ#?\\d{4}-?\\d{5}|3073598075|lumieres|viarex|revimax|celluria|viatropin|(meg|test)adrox|nordic ?loan ?firm|safflower\\Woil|(essay|resume|article|dissertation|thesis) ?writing ?service|satta ?matka|b.?o.?j.?i.?t.?e.?r', 'title': True} bad keyword in username
-- {'max_score': 1, 'username': True, 'stripcodeblocks': False, 'sites': [], 'max_rep': 4, 'body_summary': True, 'all': True, 'reason': 'bad keyword in {}', 'body': True, 'regex': '(?is)\\b()\\b|ಌ|vashi?k[ae]r[ae]n|babyli(ss|cious)|garcinia|cambogia|acai ?berr|(eye|skin|aging) ?cream|b ?a ?m ?((w ?o ?w)|(w ?a ?r))|online ?it ?guru|abam26|watch2live|cogniq|(serum|lift) ?eye|tophealth|poker[ -]?online|caralluma|male\\Wperf(?!ormer)|anti[- ]?aging|lumisse|(ultra|berry|body)[ -]?ketone|(cogni|oro)[ -]?(lift|plex)|diabazole|forskolin|tonaderm|luma(genex|lift)|(skin|face|eye)[- ]?(serum|therapy|hydration|tip|renewal|gel|lotion|cream)|(skin|eye)[- ]?lift|(skin|herbal) ?care|nuando[ -]?instant|\\bnutra|nitro[ -]?slim|aimee[ -]?cream|slimatrex|cosmitone|smile[ -]?pro[ -]?direct|bellavei|opuderm|contact (me|us)\\W*<a |follicure|kidney[ -]?bean[ -]?extract|ecoflex|\\brsgold|bellavei|goji ?xtreme|lumagenex|ajkobeshoes|kreatine|packers.{0,15}(movers|logistic).{0,25}</a>|guaranteedprofitinvestment|(brain|breast|male|penile|penis)[- ]?(enhance|enlarge|improve|boost|plus|peak)|renuva(cell|derm)| %uh | %ah |svelme|tapsi ?sarkar|viktminskning|unique(doc)?producers|green ?tone ?pro|troxyphen|seremolyn|revolyn|(?:networking|cisco|sas|hadoop|mapreduce|oracle|dba|php|sql|javascript|js|java|designing|marketing|salesforce|joomla)( certification)? (courses?|training).{0,25}</a>|(?:design|development|compan(y|ies)|training|courses?|automation)(\\b.{1,8}\\b)?\\L<city>\\b|Ｃ[Ｏ|0]Ｍ|ecoflex|no2factor|no2blast|sunergetic|capilux|sante ?avis|enduros|dianabol|ICQ#?\\d{4}-?\\d{5}|3073598075|lumieres|viarex|revimax|celluria|viatropin|(meg|test)adrox|nordic ?loan ?firm|safflower\\Woil|(essay|resume|article|dissertation|thesis) ?writing ?service|satta ?matka|b.?o.?j.?i.?t.?e.?r', 'title': True} bad keyword in body
-- {'max_score': 1, 'username': True, 'stripcodeblocks': False, 'sites': [], 'max_rep': 30, 'body_summary': True, 'all': True, 'reason': 'potentially bad keyword in {}', 'body': True, 'regex': '(?is)\\b()\\b', 'title': True} potentially bad keyword in title
-- {'max_score': 1, 'username': True, 'stripcodeblocks': False, 'sites': [], 'max_rep': 30, 'body_summary': True, 'all': True, 'reason': 'potentially bad keyword in {}', 'body': True, 'regex': '(?is)\\b()\\b', 'title': True} potentially bad keyword in username
-- {'max_score': 1, 'username': True, 'stripcodeblocks': False, 'sites': [], 'max_rep': 30, 'body_summary': True, 'all': True, 'reason': 'potentially bad keyword in {}', 'body': True, 'regex': '(?is)\\b()\\b', 'title': True} potentially bad keyword in body
-- {'max_score': 5, 'username': False, 'stripcodeblocks': False, 'sites': [], 'max_rep': 50, 'body_summary': True, 'all': True, 'reason': 'blacklisted website in {}', 'body': True, 'regex': '(?i)()', 'title': True} blacklisted website in title
-- {'max_score': 5, 'username': False, 'stripcodeblocks': False, 'sites': [], 'max_rep': 50, 'body_summary': True, 'all': True, 'reason': 'blacklisted website in {}', 'body': True, 'regex': '(?i)()', 'title': True} blacklisted website in body
-- {'max_score': 0, 'username': True, 'stripcodeblocks': False, 'sites': [], 'max_rep': 1, 'body_summary': False, 'all': True, 'reason': 'blacklisted username', 'body': False, 'regex': '(?i)()', 'title': False} blacklisted username
```
Here's the little patch I applied.
```
diff --git a/findspam.py b/findspam.py
index 977499c2..c7bef508 100644
--- a/findspam.py
+++ b/findspam.py
@@ -1054,12 +1054,15 @@ class FindSpam:
                         if matched_title:
                             result.append(rule['reason'].replace("{}", "username"))
+                            print('-- {0} {1}'.format(rule, result[-1]))
                         elif matched_body:
                             why["body"].append(u"Post - {}".format(why_post))
                             result.append(rule['reason'].replace("{}", "body"))
+                            print('-- {0} {1}'.format(rule, result[-1]))
                     else:
                         matched_title, why_title = rule['method'](post.title, post.post_site, post.user_name)
                         if matched_title and rule['title']:
@@ -1076,14 +1079,17 @@ class FindSpam:
                 if matched_title and rule['title']:
                     why["title"].append(FindSpam.generate_why(compiled_regex, post.title, u"Title", is_regex_check))
                     result.append(rule['reason'].replace("{}", "title"))
+                    print('-- {0} {1}'.format(rule, result[-1]))
                 if matched_username and rule['username']:
                                                                  is_regex_check))
                     result.append(rule['reason'].replace("{}", "username"))
+                    print('-- {0} {1}'.format(rule, result[-1]))
                 if matched_body and rule['body']:
                     why["body"].append(FindSpam.generate_why(compiled_regex, body_to_check, u"Body", is_regex_check))
                     type_of_post = "answer" if post.is_answer else "body"
                     result.append(rule['reason'].replace("{}", type_of_post))
+                    print('-- {0} {1}'.format(rule, result[-1]))
         result = list(set(result))
         result.sort()
         why = "\n".join(chain(filter(None, why["title"]), filter(None, why["body"]),
```

**Comment by tripleee** [comment]
The root cause for that is probably the same as the one I fixed, but I can't import `datahandling` from `findspam` because we end up with a circular dependency. (`datahandling` wants `metasmoke`, `metasmoke` wants `spamhandling`, `spamhandling` wants `findspam`.)

**Comment by tripleee** [comment]
My proposal would be to move the `load_blacklist()` function to a separate source module of its own. This is a bit of a mess but the whole `globalvars` morass is a much bigger, separate issue.

**Comment by tripleee** [comment]
https://github.com/tripleee/SmokeDetector/tree/no-restart-blacklists contains a commit on top of what's here which fixes the circular dependency by breaking out `load_blacklists()` into a separate file `blacklists.py`.  This is hardly ideal but allows the tests to pass.  Obviously feel free to merge it in here if you think it's useful.

**Comment by angussidney** [comment]
I'm ready to give this a test, but it is going to be a challenge.

Because all of Smokey's git integration heavily relies on our current branch config (Charcoal-SE/SmokeDetector is the assumed repo, deploy is the assumed running branch, MS only monitors specific repo/branch, etc), the only way to test this without having to make extensive local changes would be to test it in production.

I'm going to merge this branch and give it a try at about 1am UTC on Sat 22nd, providing everything goes to plan. If the test works, I'll fix any bugs and leave it in production, otherwise I'll revert all commits and we can work it out from there.

**Comment by angussidney** [comment]
!!/approve

Here it goes

**Comment by angussidney** [comment]
Merged, but not completely working. It hasn't broken anything (that I know of), but there are two issues which are preventing the no-restart part of it from working:

1. Git is outputting the diff in colour, which means that the ANSI escape codes are detected as a 'blacklist file' and thus causes Smokey to always think that files other than the blacklists are changed, meaning a full pull is required. 
    I've tried adding config options [here](https://github.com/Charcoal-SE/SmokeDetector/blob/master/gitmanager.py#L217) and [here](https://github.com/Charcoal-SE/SmokeDetector/blob/master/classes/_Git_Windows.py#L122), but the colour codes still appear. Additionally, when I run the command directly from the terminal the same production instance, there are no colours. Any ideas?

2. The strings for the [rule regexes](https://github.com/Charcoal-SE/SmokeDetector/blob/master/findspam.py#L646) have the blacklists inserted into them on startup, rather than evaluating the expression on-the-run as I originally thought. This means that the blacklists can't be easily modified at a later date. Does anyone have any good ideas on how we can get around this? Maybe create a third 'blacklist' type of check, where you pass a list along with a separator (e.g. `\b`), which are combined each time the rule is run?

**Comment by iBug** [comment]
More than a year later [this has finally been implemented][1]. The idea was similar. [Checks of global blacklists were separated][2] so they [could be modified more easily][3], Color output of Git [was disabled][4] so diff files were parsed correctly. [GlobalVars could be reloaded on-the-go][5] and then [just combine them][6] and we've got a working reboot-less blacklist reloading.

  [1]: https://github.com/Charcoal-SE/SmokeDetector/commits/master?after=9f150895b87f8c0ee19236acfef12aa3cf42f417
  [2]: https://github.com/Charcoal-SE/SmokeDetector/commit/7a4813ec5a696574ff3740f44daf981070daec9f
  [3]: https://github.com/Charcoal-SE/SmokeDetector/commit/6068c8fda1502a5624dbd77f56a7921406a1cb44
  [4]: https://github.com/Charcoal-SE/SmokeDetector/commit/1931d30804a675df07887ce0466e558167feae57
  [5]: https://github.com/Charcoal-SE/SmokeDetector/commit/d37265a13596f6a7735922d0468e412ecfb65d8f
  [6]: https://github.com/Charcoal-SE/SmokeDetector/commit/bb144eeabd69f66f53064c2e08d0c0c8b5b213ff

**Pull request merged**
