### PR TITLE
Add myself to the PullApprove list --autopull

### PR DESCRIPTION
**Pull request by bwDraco**
I've been granted code admin privileges, and this is necessary to allow me to approve watch/blacklist requests.

There was a bit of confusion on the last attempt, so I'm trying again.

### CODE REVIEW

**Comment by tripleee** [comment]
I'll be happy to merge this, but I'm on mobile right now. Properly deploying this requires you to be set up as a project collaborator or Github, then syncing that information to PullApprove. This was extremely finicky in the past, mainly perhaps because the error messages weren't very helpful.

**Comment by tripleee** [comment]
Looks like one of @Undo1 @ArtOfCode- @AWegnerGithub @angussidney will need to add you as a collaborator. https://github.com/orgs/Charcoal-SE/teams/smokedetectors/

**Comment by angussidney** [comment]
Actually, @ArtOfCode- will need to add him to the ‘other awesome people’ team. The SmokeDetectors team gives you full Git push access.

**Comment by Undo1** [comment]
Done in abf873a01d0569fa8bbc2c357f7f6782ba8539d9

**Comment by tripleee** [comment]
I updated the documentation in the wiki to reflect this.
https://github.com/Charcoal-SE/SmokeDetector/wiki/Privileges/_compare/4541bcc9cd38269fc96d3daff4000b512e8794e4...56184a13dbbecbe6b776ca9bc228370ebe0002b3

**Comment by j-f1** [comment]
@tripleee I think you just have to be a member of the organization — you don’t have to be on a team.

**Pull request closed without merging**
