### PR TITLE
Refactor blacklists; add chat commands for ip/ns/asn (#3884 take two)

### PR DESCRIPTION
**Pull request by tripleee**
This contains a major refactoring of `blacklists.py` in order to accommodate the new blacklist types properly and expose a sensible and unified API towards the calling functions in `chatcommands`, `findspam`, etc.

This is take two of #3884 which was merged and then backed out last week. I have fixed two bugs and extended the code slightly.

### CODE REVIEW

**Comment by teward** [comment]
NACK on the review - fix your Lint first.

**Review by teward — CHANGES_REQUESTED** [review]
Fix your Lintian problems

**Comment by tripleee** [comment]
I have now tried to rebase this 4-5 times and I end up with really weird results every time. Maybe I'll leave that for tomorrow.

**Comment by teward** [comment]
I would suggest splitting the "New Commands" and "Refactoring' into completely separate PRs.  I say this because I'd rather review the commands themselves independently of the "Refactor blacklists".  So I'm actually going to NACK this PR as is until you can split the two into separate PRs and issues.

**Review by teward — CHANGES_REQUESTED** [review]
See prior comment on the PR

**Comment by tripleee** [comment]
Set to pending: Thomas requested that I split off the blacklist refactoring into a separate PR which can be reviewed separately, so I will proceed to do that, in 6-8.

**Pull request closed without merging**
