### PR TITLE
Mithrandir: Blacklist amazingcart.us

### PR DESCRIPTION
**Pull request by SmokeDetector**
[Mithrandir](http://chat.stackexchange.com/users/133031) requests the blacklist of the website amazingcart.us. See the Metasmoke search [here](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=amazingcart.us)

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
/me is not entirely sure how an auto blacklist failed CI...

**Comment by teward** [comment]
Unescaped dots are evil.



*Sent from my iPhone.  Please excuse any typos, as they are likely to happen by accident.*

**Comment by ArtOfCode-** [comment]
I can excuse typos, @teward, but I'm not sure I can excuse the use of two spaces between those sentences... :P

**Comment by teward** [comment]
@ArtOfCode-  lay off, that message has been set up for an eternity on my phone as a signature for all accounts, that's from when they taught me "TWO SPACES BETWEEN SENTENCES NOOB!" :P

**Pull request merged**
