### PR TITLE
Adjusted keywords to reduce false positives.

### PR DESCRIPTION
**Pull request by BrockA**
Removed "black magic" and adjusted "weight loss" to reduce false positives.

Regarding "weight loss":

 - It was causing too many false positives due to [the term *deadweight loss*](https://en.wikipedia.org/wiki/Deadweight_loss), which frequently occurs in economics.
 - Reference [this chat on Charcoal HQ](http://chat.stackexchange.com/transcript/message/25247160#25247160)
 - Tweaked the regex to only match when word starts with "weight".

<br>
For "black magic" see:
 - Starting [here, on Tavern](http://chat.meta.stackexchange.com/transcript/message/4165391#4165391)  
  and
 - [Here, on Charcoal HQ](http://chat.stackexchange.com/transcript/message/25247400#25247400)

### CODE REVIEW

**Comment by Manishearth** [comment]
I'd rather reduce the number of sites "black magic" applies on.

There is a recurring spammer who posts about black magic.

**Comment by BrockA** [comment]
@Manishearth Okay, I'll investigate that.  I've seen nothing but false positives for it so far.

Can we kill it for now while I look into the per-site thing?

**Comment by Manishearth** [comment]
@ProgramFOX thoughts?

**Comment by BrockA** [comment]
[He already seemed to agreed to nuke it.](http://chat.meta.stackexchange.com/transcript/message/4166288#4166288)

**Comment by Manishearth** [comment]
"from Islam"

**Comment by BrockA** [comment]
You're right, but then: http://chat.stackexchange.com/transcript/message/25247400#25247400

**Comment by Manishearth** [comment]
Yes, I wonder what he says in light of the "recurring spammer" thing

**Comment by BrockA** [comment]
Can you point out some of that spam?  Might be able to fix it another way, maybe...

**Comment by Manishearth** [comment]
Well, it's all gone now :smile: 

It's similar to the vashikaran spam. It was one of the reasons we _created_ smokey in the first place.

**Comment by BrockA** [comment]
@Manishearth Okay, I put the check back in for now.   
Sure those other BM spams wouldn't have been caught by another factor? (Links, etc.) because this keyword is 0 for 3 since I started noticing it.

**Comment by Manishearth** [comment]
Not sure. r=me once travis passes

**Comment by BrockA** [comment]
Huh, wonder what the delay is...

**Comment by BrockA** [comment]
Okay @Manishearth, all checks have passed.

**Comment by BrockA** [comment]
Thanks!

**Pull request merged**
