### PR TITLE
phone number updated to include other numbers beforehand

### PR DESCRIPTION
**Pull request by WELZ-gh**
See https://chat.stackexchange.com/transcript/message/43917775#43917775

### CODE REVIEW

**Comment by WELZ-gh** [comment]
!!/approve

**Comment by iBug** [comment]
Doesn't look any necessary...

**Comment by j-f1** [comment]
How about just `\d+` at the beginning?

**Comment by tripleee** [comment]
For the record, I changed the `\W` to a `\d`

**Comment by makyen** [comment]
This is a US phone number. The only digit that's valid prior to the phone number is 1. Any other digit is much more likely to be a false positive. Another time, I'd suggest that we don't use `\d+` prior to US phone numbers, as it invites false positives.

Even though US phone numbers are only vary rarely written with a 1 immediately prior to the area code, it's possible. Thus, something like `1?833\W?783\W?3300` would be more reasonable. However, I'd consider both limiting the characters which separate the sequences and allowing more of them. Perhaps: `1?833[\s_)-]+783[\s_-]+3300`, or `1?833\W{0,3}783\W{0,3}3300`.

**Pull request merged**
