### PR TITLE
Ignore if Community user bumped post

### LINKED ISSUE #1085: Avoid catching the same post if it hasn't been modified since last report
On several occasions one sees the disambiguation screen on MS because there are multiple reports for a single posts. But many times the contents of the post are exactly the same since the last report. 

SmokeDetector can simply filter our such cases by comparing the last reported time with the last modified time of the post. Even better if it can do an exact string matching from the last report (to avoid change + rollbacks changing the modified time).

One instance of such a case is [here](https://metasmoke.erwaysoftware.com/posts/by-url?url=//dba.stackexchange.com/a/131273). 

The answer has never been edited and also has been marked as fp or naa on all the occasions. 
It was caught just because Community boosted the post.

### PR DESCRIPTION
**Pull request by paper1111**
Implements the functionality requested in #1552 

Fixes #1085

### CODE REVIEW

**Comment by iBug** [comment]
Looks very good. Are you sure MS is ignored when it's down? This happens from time to time so it's important that Smokey functions correctly during MS downtime.

**Comment by paper1111** [comment]
@iBug added a timeout so that if MS is down, it will be skipped

Quite strange that CircleCI fails while Travis passes, but anyways I think that's not my fault.

**Comment by iBug** [comment]
You're running CircleCI with an already discontinued version of `tld`. Try overwriting your `user_requirements.txt` with the one in the master branch.

Travis CI is installing and updating dependencies on every run, while CircleCI only updates them if they no longer meets the requirements specified in the repository. This is why Travis is using the correct version but Circle sticks to an old version.

**Comment by paper1111** [comment]
@iBug it **is** checked already

**Comment by paper1111** [comment]
ummm... I edited the file but it still failed with the same issue..?

**Comment by iBug** [comment]
From the build logs, it seems Circle pulls and tests your working tree directly, while Travis pulls the target branch (`Charcoal-SE:master`) and merges your branch in. This means Travis tests the state after the PR should be merged.

`tld` has updated to 0.9, which contains backward-incompatible change that breaks your code (you started this PR from a state in mid-May, which doesn't contain any patches for `tld` 0.8+). Since the master branch is already adapted for `tld` 0.8+, your code passes the tests after being merged with master. This is why Travis and Circle are giving different results.

Anyway, since Circle is fixed now, you can ignore this.

**Comment by paper1111** [comment]
Great, thanks!

**Pull request merged**
