### PR TITLE
Exclude bad NS from git check

### PR DESCRIPTION
**Pull request by tripleee**
Don't require -force to blacklist or watch something which is triggered by these rules.

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
What's the rationale here? Why should this reason exempt a domain from the usual blacklisting requirements?

**Comment by j-f1** [comment]
> Why should this reason exempt a domain from the usual blacklisting requirements?

Because a spammer could change the domain to be on another NS, but blacklisting will still be effective.

**Comment by tripleee** [comment]
I agree that that's a useful discussion to have, but it's a broader issue than this one. If we agree that "bad NS" is solid enough on its own, maybe this PR should simply just be rejected for now. But then shouldn't we have more granular control across the board? I'd like for blacklisted X (including blacklisted NS) to be split into "really blacklisted X" (which should have basically 100% accuracy and a weight of 100, or even pinned to an even higher weight) and "suspicious X" (which can collect any number of speculative terms which may accrue FPs occasionally, and have the weight calculated accordingly).

**Comment by ArtOfCode-** [comment]
That's what blacklisting and watching are for, @tripleee. The idea behind blacklisting requirements is that it's only going on the blacklist if we're absolutely sure it's spam.

**Comment by tripleee** [comment]
Indeed, but there are terms and regexes within those lists which were added before we had a defined policy, or in violation of the policy, or which ended up producing false positives for whatever reason. What I'm trying to suggest is to make this three-way: watch (speculative heuristic, no substantial weight), suspicious (thought to be good heuristic, let it contribute to the weight according to the formula) and really black (basically proven good enough to autoflag by itself, though we may want to be slightly more conservative than that).

**Comment by ArtOfCode-** [comment]
That sounds like excess complexity to me. Surely it'd be better to clean up the existing lists? Three lists makes an already complicated system even more effort to learn about.

**Comment by quartata** [comment]
Why was this closed? I think all of this discussion is missing the point: checking NS is for discovering domains that *should* be blacklisted -- we shouldn't then discourage people from blacklisting them by making them use `-force`.

**Comment by ArtOfCode-** [comment]
Closed because lack of activity. That doesn't mean no discussion.

**Pull request closed without merging**
