### PR TITLE
Use raw string for anchoring

### PR DESCRIPTION
**Pull request by user12986714**

### CODE REVIEW

**Comment by user12986714** [comment]
Bug fix

**Comment by makyen** [comment]
While this is also needed, it's not fixing all the problems.

**Comment by user12986714** [comment]
Yeah

**Comment by makyen** [comment]
You are substituting into a URL. That's what the `quote_plus()` was for. It's still needed.

**Comment by makyen** [comment]
In other words, the line that calls `_anchor()` should be:

    quote_plus(_anchor(item, blacklist_type)),

**Comment by user12986714** [comment]
I suppose by not performing inspections before submitting code, I have taken the watch/blacklist pr-ing functionality down for at least 15 minutes... :-(

**Comment by makyen** [comment]
No, it's not *actually* broken. What's shown in the comments on auto-PRs is broken, but it didn't actually affect the changes the PRs made. Less convenient, yes. Dead, no.

**Comment by makyen** [comment]
Besides, it's at least as much on me for not doing a good job reviewing the original PR.

**Comment by makyen** [comment]
!!/approve

**Pull request merged**
