### PR TITLE
NobodyNada: Blacklist geekformac.zoomsupport.com

### PR DESCRIPTION
**Pull request by SmokeDetector**
[NobodyNada](http://chat.stackexchange.com/users/139423) requests the blacklist of the website geekformac.zoomsupport.com. See the Metasmoke search [here](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=geekformac.zoomsupport.com)

### CODE REVIEW

**Comment by NobodyNada** [comment]
We might consider just blacklisting `zoomsupport.com` instead of `geeksformac.zoomsupport.com`

**Comment by teward** [comment]
You forgot this is a regex pattern.  You need to escape the `.`

**Comment by teward** [comment]
If the builds succeed, I'll merge this.

**Comment by NobodyNada** [comment]
Oops, my mistake.  Thanks!

**Pull request merged**
