### PR TITLE
bwDraco: Blacklist Marlin\, Woods

### PR DESCRIPTION
**Pull request by SmokeDetector**
bwDraco requests blacklist of domains: 

 - Marlin\ - [MS search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=Marlin\)
 - Woods - [MS search](https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&body_is_regex=1&body=Woods)

### CODE REVIEW

**Comment by bwDraco** [comment]
Please disregard this; this seems to be a mistake.

The intent here is to have the username "Marlin Woods" blacklisted due to ongoing trolling by the user, repeatedly posting plagiarized content on Super User and creating new (unregistered) accounts with the same name each time it does so.

**Comment by Fortunate-MAN** [comment]
ok, I'm closing this then.

**Comment by ArtOfCode-** [comment]
@bwDraco The `!!/blacklist` command adds a *website* to the blacklist - usernames are still handled somewhere else, and need code modifications to do. Which is not to say that you can't do it, just that `!!/blacklist` isn't the tool you're looking for.

**Comment by bwDraco** [comment]
That makes sense now, thanks.

**Pull request closed without merging**
