### PR TITLE
!!/unnotify shorthand

### LINKED ISSUE #1164: !!/notify works with the short URL version, but !!/unnotify doesn't
This came up earlier with @NVZ in chat - he was trying to !!/unnotify from interpersonal.stackexchange.com, but was trying with just 'interpersonal'... since that's how he did !!/notify.

Can !!/unnotify work without the .stackexchange.com as well?

### PR DESCRIPTION
**Pull request by paper1111**
This fixes #1164 (the shorthand for !!/unnotify)

### CODE REVIEW

**Comment by paper1111** [comment]
So... when will this be merged?

**Comment by j-f1** [comment]
Looks great @paper1111. Tip: if you edit the initial PR comment to say `fixes #1164`, the issue will automatically be closed when the PR gets merged.

**Comment by paper1111** [comment]
@j-f1 is it like this?

**Comment by j-f1** [comment]
Yes!

**Pull request merged**
