### PR TITLE
Update findspam.py

### PR DESCRIPTION
**Pull request by K-Davis1**
# NSFW

Inspired by https://m.erwaysoftware.com/posts/by-url?url=//hinduism.stackexchange.com/a/26263

### CODE REVIEW

**Comment by iBug** [comment]
Most are probably one-hit-and-never. I don't think most of these would be effective in long run.

**Comment by K-Davis1** [comment]
@iBug really? This guy has been posting the same "story" for the last two weeks. And it continues to occur.

https://metasmoke.erwaysoftware.com/search?utf8=%E2%9C%93&title=&body=sexy+DURGA&username=&why=&site=249&post_type=&feedback=&autoflagged=&reason=&user_rep_direction=%3E%3D&user_reputation=0&commit=Search

And the last report was manually submitted. So you're saying you don't want to catch this stuff?

**Comment by iBug** [comment]
I mean, I doubt they will catch a lot in the future (effectiveness).

**Comment by angussidney** [comment]
!!/approve

**Comment by angussidney** [comment]
!!/approve (now with changes)

**Pull request merged**
