### PR TITLE
Fixed regex causing FP on white spaces

### PR DESCRIPTION
**Pull request by kishan-1234**
Added check in regex to ignore whitespaces

### CODE REVIEW

**Comment by iBug** [comment]
Looks good. You may want to escape the backslashes in the string so Python parses them as blackslashes instead of parsing `\s` as an escape sequence.

**Comment by kishan-1234** [comment]
@iBug I didn't get your point regarding escaping the backslashes. Can you please explain further, it would be very helpful if you could give an example where regex fails in this regard.

**Comment by iBug** [comment]
There's nothing wrong with the regex, but that it's a Python string:

```python
>>> print("\s")
\s
>>> print(u"\s\n")
\s

>>> print(u"\\s\\n")
\s\n
```

While it doesn't matter here, it's better to escape the backslashes.

**Comment by kishan-1234** [comment]
Thanks for explaining @iBug  !!

If the regex is correct, escaping the backslash in the input string might require code changes in some different module/location right?. Please correct me if am wrong

**Comment by ArtOfCode-** [comment]
The easy way to do what @iBug is suggesting is to change `u"..."` (unicode string) to `r"..."` ('raw' string). All strings in Python 3 are automatically unicode strings, so you don't need the `u`, and adding the `r` means you don't need to escape backslashes (which is what's done elsewhere in the file, if you want some examples of that).

**Comment by iBug** [comment]
@ArtOfCode- 

```
u"...['\"]+\s*"
       ^^
```

**Comment by ArtOfCode-** [comment]
@iBug Not sure I understand what you're getting at there.

**Comment by kishan-1234** [comment]
Thanks a lot @ArtOfCode- !!

Done the change.

**Comment by iBug** [comment]
Looks good enough now.

**Pull request merged**
